
default: &default
  adapter: postgresql
  encoding: unicode
  username: test
  password: password
  pool: 5
  host: 127.0.0.1

development:
  <<: *default
  database: my_shop_development
test:
  <<: *default
  database: my_shop_test

production:
  <<: *default
  database: my_shop_production
  username: my_shop
  password: <%= ENV['MY_SHOP_DATABASE_PASSWORD'] %>
